commands:
  - aliases:
      - h
      - home
    command: cd ~
  - aliases:
      - p
      - personal
    command: cd d:/personal
  - aliases:
      - dotfiles
      - dotfile
      - dot
    command: cd d:/personal/dotfiles
  - aliases:
      - nvim
      - vim
    command: cd ~/appdata/local/nvim
  - aliases:
      - vine
    command: cd d:/personal/vine
  - aliases:
      - pi
      - conpi
    command: ./vine_scripts/connectPISSH.sh
